apiVersion: v1
kind: Service
metadata:
  name: cal-diary
  namespace: cal-diary
  labels:
    app: cal-diary
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  type: LoadBalancer
  selector:
    app: cal-diary
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http
